-- 0010_expand_taxonomy.sql
-- Expanded industry taxonomy (industry -> capability), mirroring prisma/seed.ts.
-- Idempotent: unique slugs + ON CONFLICT DO NOTHING, so existing rows and any
-- advisor's current selections are left untouched. Safe to re-run. This is a
-- pure-SQL alternative to `npm run db:seed` for applying via the SQL editor.
--
-- IDs are opaque text; gen_random_uuid()::text is fine (Prisma reads them as-is).

-- Industries (parent rows).
insert into public.industry_taxonomy (id, name, slug) values
  (gen_random_uuid()::text, 'Manufacturing & Production', 'manufacturing-and-production'),
  (gen_random_uuid()::text, 'Construction & Trades', 'construction-and-trades'),
  (gen_random_uuid()::text, 'Retail & E-commerce', 'retail-and-e-commerce'),
  (gen_random_uuid()::text, 'Hospitality & Food Service', 'hospitality-and-food-service'),
  (gen_random_uuid()::text, 'Professional Services', 'professional-services'),
  (gen_random_uuid()::text, 'Healthcare & Care', 'healthcare-and-care'),
  (gen_random_uuid()::text, 'Technology & Software', 'technology-and-software'),
  (gen_random_uuid()::text, 'Finance & Accounting', 'finance-and-accounting'),
  (gen_random_uuid()::text, 'Agriculture & Primary', 'agriculture-and-primary'),
  (gen_random_uuid()::text, 'Transport & Logistics', 'transport-and-logistics'),
  (gen_random_uuid()::text, 'Energy & Utilities', 'energy-and-utilities'),
  (gen_random_uuid()::text, 'Creative & Media', 'creative-and-media'),
  (gen_random_uuid()::text, 'Education & Training', 'education-and-training'),
  (gen_random_uuid()::text, 'Real Estate & Property', 'real-estate-and-property'),
  (gen_random_uuid()::text, 'Nonprofit & Social Enterprise', 'nonprofit-and-social-enterprise'),
  (gen_random_uuid()::text, 'Other / Cross-industry', 'other-cross-industry')
on conflict (slug) do nothing;

-- Capabilities (children), joined to their parent by slug so this works whether
-- the parent already existed or was just inserted above.
insert into public.industry_taxonomy (id, name, slug, parent_id)
select gen_random_uuid()::text, v.name, v.slug, p.id
from (values
  ('Operations & throughput', 'manufacturing-and-production--operations-and-throughput', 'manufacturing-and-production'),
  ('Quality & compliance', 'manufacturing-and-production--quality-and-compliance', 'manufacturing-and-production'),
  ('Supply chain & procurement', 'manufacturing-and-production--supply-chain-and-procurement', 'manufacturing-and-production'),
  ('Health & safety', 'manufacturing-and-production--health-and-safety', 'manufacturing-and-production'),
  ('Automation & lean', 'manufacturing-and-production--automation-and-lean', 'manufacturing-and-production'),
  ('Cost reduction', 'manufacturing-and-production--cost-reduction', 'manufacturing-and-production'),
  ('Product development', 'manufacturing-and-production--product-development', 'manufacturing-and-production'),
  ('Maintenance & reliability', 'manufacturing-and-production--maintenance-and-reliability', 'manufacturing-and-production'),
  ('Other (not listed)', 'manufacturing-and-production--other-not-listed', 'manufacturing-and-production'),
  ('Estimating & tendering', 'construction-and-trades--estimating-and-tendering', 'construction-and-trades'),
  ('Project management', 'construction-and-trades--project-management', 'construction-and-trades'),
  ('Regulatory & certification', 'construction-and-trades--regulatory-and-certification', 'construction-and-trades'),
  ('Subcontractor management', 'construction-and-trades--subcontractor-management', 'construction-and-trades'),
  ('Contracts & disputes', 'construction-and-trades--contracts-and-disputes', 'construction-and-trades'),
  ('WHS & site safety', 'construction-and-trades--whs-and-site-safety', 'construction-and-trades'),
  ('Cash flow & retention', 'construction-and-trades--cash-flow-and-retention', 'construction-and-trades'),
  ('Sustainability & green building', 'construction-and-trades--sustainability-and-green-building', 'construction-and-trades'),
  ('Other (not listed)', 'construction-and-trades--other-not-listed', 'construction-and-trades'),
  ('Merchandising & buying', 'retail-and-e-commerce--merchandising-and-buying', 'retail-and-e-commerce'),
  ('Inventory & fulfilment', 'retail-and-e-commerce--inventory-and-fulfilment', 'retail-and-e-commerce'),
  ('Pricing & margin', 'retail-and-e-commerce--pricing-and-margin', 'retail-and-e-commerce'),
  ('Storefront & online conversion', 'retail-and-e-commerce--storefront-and-online-conversion', 'retail-and-e-commerce'),
  ('Marketing & customer acquisition', 'retail-and-e-commerce--marketing-and-customer-acquisition', 'retail-and-e-commerce'),
  ('Marketplaces & omnichannel', 'retail-and-e-commerce--marketplaces-and-omnichannel', 'retail-and-e-commerce'),
  ('Loyalty & retention', 'retail-and-e-commerce--loyalty-and-retention', 'retail-and-e-commerce'),
  ('International expansion', 'retail-and-e-commerce--international-expansion', 'retail-and-e-commerce'),
  ('Other (not listed)', 'retail-and-e-commerce--other-not-listed', 'retail-and-e-commerce'),
  ('Kitchen & menu operations', 'hospitality-and-food-service--kitchen-and-menu-operations', 'hospitality-and-food-service'),
  ('Front-of-house & service', 'hospitality-and-food-service--front-of-house-and-service', 'hospitality-and-food-service'),
  ('Licensing & food safety', 'hospitality-and-food-service--licensing-and-food-safety', 'hospitality-and-food-service'),
  ('Multi-site expansion', 'hospitality-and-food-service--multi-site-expansion', 'hospitality-and-food-service'),
  ('Cost & margin control', 'hospitality-and-food-service--cost-and-margin-control', 'hospitality-and-food-service'),
  ('Staffing & culture', 'hospitality-and-food-service--staffing-and-culture', 'hospitality-and-food-service'),
  ('Marketing & bookings', 'hospitality-and-food-service--marketing-and-bookings', 'hospitality-and-food-service'),
  ('Franchising', 'hospitality-and-food-service--franchising', 'hospitality-and-food-service'),
  ('Other (not listed)', 'hospitality-and-food-service--other-not-listed', 'hospitality-and-food-service'),
  ('Practice management', 'professional-services--practice-management', 'professional-services'),
  ('Pricing & packaging', 'professional-services--pricing-and-packaging', 'professional-services'),
  ('Client acquisition', 'professional-services--client-acquisition', 'professional-services'),
  ('Team & delivery', 'professional-services--team-and-delivery', 'professional-services'),
  ('Operations & systems', 'professional-services--operations-and-systems', 'professional-services'),
  ('Partnerships & M&A', 'professional-services--partnerships-and-manda', 'professional-services'),
  ('Marketing & brand', 'professional-services--marketing-and-brand', 'professional-services'),
  ('Succession & exit', 'professional-services--succession-and-exit', 'professional-services'),
  ('Other (not listed)', 'professional-services--other-not-listed', 'professional-services'),
  ('Clinical operations', 'healthcare-and-care--clinical-operations', 'healthcare-and-care'),
  ('Regulatory & accreditation', 'healthcare-and-care--regulatory-and-accreditation', 'healthcare-and-care'),
  ('Staffing & rostering', 'healthcare-and-care--staffing-and-rostering', 'healthcare-and-care'),
  ('Patient/resident experience', 'healthcare-and-care--patient-resident-experience', 'healthcare-and-care'),
  ('Funding & billing', 'healthcare-and-care--funding-and-billing', 'healthcare-and-care'),
  ('Quality & clinical risk', 'healthcare-and-care--quality-and-clinical-risk', 'healthcare-and-care'),
  ('Growth & new services', 'healthcare-and-care--growth-and-new-services', 'healthcare-and-care'),
  ('Digital health & records', 'healthcare-and-care--digital-health-and-records', 'healthcare-and-care'),
  ('Other (not listed)', 'healthcare-and-care--other-not-listed', 'healthcare-and-care'),
  ('Product & roadmap', 'technology-and-software--product-and-roadmap', 'technology-and-software'),
  ('Engineering delivery', 'technology-and-software--engineering-delivery', 'technology-and-software'),
  ('Go-to-market', 'technology-and-software--go-to-market', 'technology-and-software'),
  ('Scaling & hiring', 'technology-and-software--scaling-and-hiring', 'technology-and-software'),
  ('Fundraising & finance', 'technology-and-software--fundraising-and-finance', 'technology-and-software'),
  ('Security & compliance', 'technology-and-software--security-and-compliance', 'technology-and-software'),
  ('Customer success & retention', 'technology-and-software--customer-success-and-retention', 'technology-and-software'),
  ('Data & AI', 'technology-and-software--data-and-ai', 'technology-and-software'),
  ('Other (not listed)', 'technology-and-software--other-not-listed', 'technology-and-software'),
  ('Cash flow & working capital', 'finance-and-accounting--cash-flow-and-working-capital', 'finance-and-accounting'),
  ('Financial controls', 'finance-and-accounting--financial-controls', 'finance-and-accounting'),
  ('Tax & compliance', 'finance-and-accounting--tax-and-compliance', 'finance-and-accounting'),
  ('Fundraising & lending', 'finance-and-accounting--fundraising-and-lending', 'finance-and-accounting'),
  ('Systems & automation', 'finance-and-accounting--systems-and-automation', 'finance-and-accounting'),
  ('Reporting & forecasting', 'finance-and-accounting--reporting-and-forecasting', 'finance-and-accounting'),
  ('M&A & exit', 'finance-and-accounting--manda-and-exit', 'finance-and-accounting'),
  ('Payroll & bookkeeping', 'finance-and-accounting--payroll-and-bookkeeping', 'finance-and-accounting'),
  ('Other (not listed)', 'finance-and-accounting--other-not-listed', 'finance-and-accounting'),
  ('Farm operations', 'agriculture-and-primary--farm-operations', 'agriculture-and-primary'),
  ('Compliance & certification', 'agriculture-and-primary--compliance-and-certification', 'agriculture-and-primary'),
  ('Supply agreements', 'agriculture-and-primary--supply-agreements', 'agriculture-and-primary'),
  ('Succession & transition', 'agriculture-and-primary--succession-and-transition', 'agriculture-and-primary'),
  ('Sustainability & environment', 'agriculture-and-primary--sustainability-and-environment', 'agriculture-and-primary'),
  ('Diversification & value-add', 'agriculture-and-primary--diversification-and-value-add', 'agriculture-and-primary'),
  ('Labour & workforce', 'agriculture-and-primary--labour-and-workforce', 'agriculture-and-primary'),
  ('Water & land management', 'agriculture-and-primary--water-and-land-management', 'agriculture-and-primary'),
  ('Other (not listed)', 'agriculture-and-primary--other-not-listed', 'agriculture-and-primary'),
  ('Fleet & operations', 'transport-and-logistics--fleet-and-operations', 'transport-and-logistics'),
  ('Route & cost optimisation', 'transport-and-logistics--route-and-cost-optimisation', 'transport-and-logistics'),
  ('Compliance & licensing', 'transport-and-logistics--compliance-and-licensing', 'transport-and-logistics'),
  ('Warehousing', 'transport-and-logistics--warehousing', 'transport-and-logistics'),
  ('Technology & tracking', 'transport-and-logistics--technology-and-tracking', 'transport-and-logistics'),
  ('Safety & fatigue management', 'transport-and-logistics--safety-and-fatigue-management', 'transport-and-logistics'),
  ('Customer & contracts', 'transport-and-logistics--customer-and-contracts', 'transport-and-logistics'),
  ('Last-mile & delivery', 'transport-and-logistics--last-mile-and-delivery', 'transport-and-logistics'),
  ('Other (not listed)', 'transport-and-logistics--other-not-listed', 'transport-and-logistics'),
  ('Operations & maintenance', 'energy-and-utilities--operations-and-maintenance', 'energy-and-utilities'),
  ('Regulatory & safety', 'energy-and-utilities--regulatory-and-safety', 'energy-and-utilities'),
  ('Sustainability & transition', 'energy-and-utilities--sustainability-and-transition', 'energy-and-utilities'),
  ('Asset management', 'energy-and-utilities--asset-management', 'energy-and-utilities'),
  ('Project delivery', 'energy-and-utilities--project-delivery', 'energy-and-utilities'),
  ('Commercial & pricing', 'energy-and-utilities--commercial-and-pricing', 'energy-and-utilities'),
  ('Grid & network', 'energy-and-utilities--grid-and-network', 'energy-and-utilities'),
  ('Renewables & storage', 'energy-and-utilities--renewables-and-storage', 'energy-and-utilities'),
  ('Other (not listed)', 'energy-and-utilities--other-not-listed', 'energy-and-utilities'),
  ('Studio operations', 'creative-and-media--studio-operations', 'creative-and-media'),
  ('Commercial & rights', 'creative-and-media--commercial-and-rights', 'creative-and-media'),
  ('Client & project delivery', 'creative-and-media--client-and-project-delivery', 'creative-and-media'),
  ('Talent & team', 'creative-and-media--talent-and-team', 'creative-and-media'),
  ('Marketing & audience', 'creative-and-media--marketing-and-audience', 'creative-and-media'),
  ('Finance & pricing', 'creative-and-media--finance-and-pricing', 'creative-and-media'),
  ('IP & licensing', 'creative-and-media--ip-and-licensing', 'creative-and-media'),
  ('Digital & content strategy', 'creative-and-media--digital-and-content-strategy', 'creative-and-media'),
  ('Other (not listed)', 'creative-and-media--other-not-listed', 'creative-and-media'),
  ('Programme design', 'education-and-training--programme-design', 'education-and-training'),
  ('Accreditation & compliance', 'education-and-training--accreditation-and-compliance', 'education-and-training'),
  ('Enrolment & growth', 'education-and-training--enrolment-and-growth', 'education-and-training'),
  ('Operations', 'education-and-training--operations', 'education-and-training'),
  ('Curriculum & delivery', 'education-and-training--curriculum-and-delivery', 'education-and-training'),
  ('Digital & online learning', 'education-and-training--digital-and-online-learning', 'education-and-training'),
  ('Funding & partnerships', 'education-and-training--funding-and-partnerships', 'education-and-training'),
  ('Student experience', 'education-and-training--student-experience', 'education-and-training'),
  ('Other (not listed)', 'education-and-training--other-not-listed', 'education-and-training'),
  ('Development & feasibility', 'real-estate-and-property--development-and-feasibility', 'real-estate-and-property'),
  ('Property management', 'real-estate-and-property--property-management', 'real-estate-and-property'),
  ('Compliance & leasing', 'real-estate-and-property--compliance-and-leasing', 'real-estate-and-property'),
  ('Investment strategy', 'real-estate-and-property--investment-strategy', 'real-estate-and-property'),
  ('Financing & capital', 'real-estate-and-property--financing-and-capital', 'real-estate-and-property'),
  ('Sales & marketing', 'real-estate-and-property--sales-and-marketing', 'real-estate-and-property'),
  ('Sustainability & ESG', 'real-estate-and-property--sustainability-and-esg', 'real-estate-and-property'),
  ('Facilities & operations', 'real-estate-and-property--facilities-and-operations', 'real-estate-and-property'),
  ('Other (not listed)', 'real-estate-and-property--other-not-listed', 'real-estate-and-property'),
  ('Funding & grants', 'nonprofit-and-social-enterprise--funding-and-grants', 'nonprofit-and-social-enterprise'),
  ('Governance & compliance', 'nonprofit-and-social-enterprise--governance-and-compliance', 'nonprofit-and-social-enterprise'),
  ('Programme delivery', 'nonprofit-and-social-enterprise--programme-delivery', 'nonprofit-and-social-enterprise'),
  ('Impact measurement', 'nonprofit-and-social-enterprise--impact-measurement', 'nonprofit-and-social-enterprise'),
  ('Fundraising & development', 'nonprofit-and-social-enterprise--fundraising-and-development', 'nonprofit-and-social-enterprise'),
  ('Volunteer & workforce', 'nonprofit-and-social-enterprise--volunteer-and-workforce', 'nonprofit-and-social-enterprise'),
  ('Strategy & scaling', 'nonprofit-and-social-enterprise--strategy-and-scaling', 'nonprofit-and-social-enterprise'),
  ('Partnerships & advocacy', 'nonprofit-and-social-enterprise--partnerships-and-advocacy', 'nonprofit-and-social-enterprise'),
  ('Other (not listed)', 'nonprofit-and-social-enterprise--other-not-listed', 'nonprofit-and-social-enterprise'),
  ('Strategy & leadership', 'other-cross-industry--strategy-and-leadership', 'other-cross-industry'),
  ('Finance & funding', 'other-cross-industry--finance-and-funding', 'other-cross-industry'),
  ('Sales & marketing', 'other-cross-industry--sales-and-marketing', 'other-cross-industry'),
  ('People & culture', 'other-cross-industry--people-and-culture', 'other-cross-industry'),
  ('Operations & systems', 'other-cross-industry--operations-and-systems', 'other-cross-industry'),
  ('Legal & compliance', 'other-cross-industry--legal-and-compliance', 'other-cross-industry'),
  ('Digital & technology', 'other-cross-industry--digital-and-technology', 'other-cross-industry'),
  ('Turnaround & exit', 'other-cross-industry--turnaround-and-exit', 'other-cross-industry'),
  ('Other (not listed)', 'other-cross-industry--other-not-listed', 'other-cross-industry')
) as v(name, slug, parent_slug)
join public.industry_taxonomy p on p.slug = v.parent_slug
on conflict (slug) do nothing;
